repositories {
    // Gradle Base Stuff
    mavenCentral()
    google() // Needed for androidx
    // Pedro Pathing
    maven { url = 'https://maven.pedropathing.com' } //added by Tanner
    maven { url = "https://mymaven.bylazar.com/releases" } //added by Tanner
}

dependencies {
    implementation 'org.firstinspires.ftc:Inspection:12.0.0'
    implementation 'org.firstinspires.ftc:Blocks:12.0.0'
    implementation 'org.firstinspires.ftc:RobotCore:12.0.0'
    implementation 'org.firstinspires.ftc:RobotServer:12.0.0'
    implementation 'org.firstinspires.ftc:OnBotJava:12.0.0'
    implementation 'org.firstinspires.ftc:Hardware:12.0.0'
    implementation 'org.firstinspires.ftc:FtcCommon:12.0.0'
    implementation 'org.firstinspires.ftc:Vision:12.0.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    // Gradle Base Stuff
    implementation 'org.firstinspires.ftc:Inspection:12.0.0'
    implementation 'org.firstinspires.ftc:Blocks:12.0.0'
    //noinspection Aligned16KB
    implementation 'org.firstinspires.ftc:RobotCore:12.0.0'
    implementation 'org.firstinspires.ftc:RobotServer:12.0.0'
    implementation 'org.firstinspires.ftc:OnBotJava:12.0.0'
    implementation 'org.firstinspires.ftc:Hardware:12.0.0'
    implementation 'org.firstinspires.ftc:FtcCommon:12.0.0'
    implementation 'org.firstinspires.ftc:Vision:12.0.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    // Pedro Pathing
    implementation 'com.pedropathing:ftc:2.1.2' //added by Tanner
    implementation 'com.pedropathing:telemetry:1.0.0' //added by Tanner
    implementation 'com.bylazar:fullpanels:1.0.12' //added by Tanner
}

